version: '2'

services:
  web:
    build: .
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./example-app/public:/var/www/localhost/htdocs/public
      - ~/.ssh:/root/.ssh:ro
      - ./passthru:/passthru